// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiclesAPI.Context;

namespace VehiclesAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220613163710_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehiclesAPI.Models.Concrete.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            Model = "Raptor"
                        },
                        new
                        {
                            Id = 2,
                            Color = "blue",
                            Model = "Terhi"
                        },
                        new
                        {
                            Id = 3,
                            Color = "black",
                            Model = "Hydrolift"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Model = "Terhi"
                        },
                        new
                        {
                            Id = 5,
                            Color = "white",
                            Model = "Raptor"
                        },
                        new
                        {
                            Id = 6,
                            Color = "black",
                            Model = "Raptor"
                        },
                        new
                        {
                            Id = 7,
                            Color = "red",
                            Model = "Raptor"
                        },
                        new
                        {
                            Id = 8,
                            Color = "red",
                            Model = "Hydrolift"
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            Model = "Hydrolift"
                        },
                        new
                        {
                            Id = 10,
                            Color = "black",
                            Model = "Terhi"
                        });
                });

            modelBuilder.Entity("VehiclesAPI.Models.Concrete.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            Model = "BMC"
                        },
                        new
                        {
                            Id = 2,
                            Color = "blue",
                            Model = "Man"
                        },
                        new
                        {
                            Id = 3,
                            Color = "black",
                            Model = "Setra"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Model = "Setra"
                        },
                        new
                        {
                            Id = 5,
                            Color = "white",
                            Model = "BMC"
                        },
                        new
                        {
                            Id = 6,
                            Color = "black",
                            Model = "BMC"
                        },
                        new
                        {
                            Id = 7,
                            Color = "red",
                            Model = "Man"
                        },
                        new
                        {
                            Id = 8,
                            Color = "red",
                            Model = "Man"
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            Model = "Man"
                        },
                        new
                        {
                            Id = 10,
                            Color = "black",
                            Model = "Setra"
                        });
                });

            modelBuilder.Entity("VehiclesAPI.Models.Concrete.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeadLight")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wheel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            HeadLight = false,
                            Model = "BMW",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 2,
                            Color = "blue",
                            HeadLight = false,
                            Model = "Mercedes",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 3,
                            Color = "black",
                            HeadLight = false,
                            Model = "Lamborghini",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            HeadLight = false,
                            Model = "Mercedes",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "white",
                            HeadLight = false,
                            Model = "Lamborghini",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 6,
                            Color = "black",
                            HeadLight = false,
                            Model = "BMW",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 7,
                            Color = "red",
                            HeadLight = false,
                            Model = "BMW",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 8,
                            Color = "red",
                            HeadLight = false,
                            Model = "Lamborghini",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 9,
                            Color = "blue",
                            HeadLight = false,
                            Model = "Lamborghini",
                            Wheel = 4
                        },
                        new
                        {
                            Id = 10,
                            Color = "black",
                            HeadLight = false,
                            Model = "BMW",
                            Wheel = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
